### PR TITLE
Ignore "/" when updating track numbers to 2 digits

### PR DESCRIPTION
**Pull request by SeanKilleen**
## Firstly: Hello!

First of all, I want to say that this app is absolutely awesome and has given me a ton of joy to organize my music. It's really nicely done and I've cleaned up years of music. THANK YOU!

## Background
When utilizing the 2-digit track number script, I realized it had an error on some of my tracks with fractional track numbers (e.g. 1/10, 2/10, etc.)

## This PR

* Ignores text after the track number
* Adds some comments

## Testing

I've used this on ~5,000 songs while cleaning up my library and it hasn't failed once. 😄

### CODE REVIEW

**Comment by CyberSinh** [comment]
Hi. Thank you very much for your encouragement. There is already a script named "Split track number" which remove text after the '/' character. I'm not sure it's relevant to make this script more complex to combine the effects of existing scripts. What do you think of that?

**Comment by SeanKilleen** [comment]
In this case, I wanted to have the double-digit track number without having it error out on the `/` in the track number. Running the script as-is caused many errors, and if I was to keep this script i would have needed to run multiple scripts.

I won't be offended if you close this & don't accept the contribution, but wanted to offer it.

**Comment by CyberSinh** [comment]
On reflection, I think that the script should indeed take into account the possible presence of the "/" character, but without deleting the text after it because the user can legitimately expect that this script will only add 0s without deleting anything. The user who wants to truncate track number tags will use the "split track number" script. So I modified the script accordingly. Please see https://github.com/luminescence-software/scripts/commit/0a19ffd1be2a7bde737351dd24ba4be062452fbb

**Comment by SeanKilleen** [comment]
@CyberSinh OK. From an OSS, I would have preferred to make the modifications here and have the PR accepted instead. But thanks for improving it regardless!

**Pull request closed without merging**
